#!/usr/bin/expect

set prompt "raspberry-pi"
#set prompt "ban"
#set prompt "tjava.rhcloud"
#set prompt alarmpi

#puts stdout $prompt

set id "192.168.1.105"
#set id "192.168.188.44"

set radio [lindex $argv 0]

if { [lindex $argv 0] eq "" } {
    set radio "Radio Int."
}

spawn ssh $id
#spawn rhc ssh django

expect "password"
send "p\r"

expect  $prompt {

send [lindex $argv 0]\r

#send ex\r
}

interact

