#!/usr/bin/expect

#set prompt alarmpi
set prompt "ban"
#set prompt "raspberry-pi"

#set prompt "tjava.rhcloud"

#set id "192.168.1.105"
set id "192.168.188.44"

set green "\033\[0;32;40m"


if { [lindex $argv 0] eq "-h" } {
    puts "${green}Argumente\n Argument 1: standard\r
    Arg. 2: exit"
    exit 0
}

spawn ssh $id
#spawn rhc ssh django

expect "password"
send "p\r"

expect  $prompt {

send_user "Skript: $argv0 [lrange $argv 0 2]\n"

send [lindex $argv 0]\r

if { [lindex $argv 1] ne "" } {
send ex\r
}

if { [lindex $argv 0] ne "" } {
    send [lindex $argv 0]\r
}


}

interact

