#!/bin/bash

omz=$HOME/.oh-my-zsh
#echo $omz

omz_cu=$omz/custom

#chsh -s /bin/zsh

sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

#rm -rf $omz_cu

#cd $omz
git clone git@github.com:tik9/custom

#cp $omz_cu/.zshrc $HOME

git config --global user.email ""

git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions